name: RestAssured API Testing CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build, Run Tests, and Generate Cucumber Report
        run: mvn clean test

      # Optional: Ensure folder exists (for debugging / empty reports)
      #- name: Debug - create cucumber-reports folder if not generated
        #run: mkdir -p target/cucumber-reports

      - name: Archive Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports
          path: target/surefire-reports/

      - name: Archive Cucumber HTML Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-html-report
          path: target/cucumber-reports/
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
